import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"   // ← corrected names
import "./globals.css"
import { ThemeProvider } from "next-themes"
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "RM Indirex Studio",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning  // ← add this too
        data-new-gr-c-s-check-loaded="14.1269.0"  // match the version in your error
        data-gr-ext-installed=""
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem={false}
          disableTransitionOnChange
          enableColorScheme={false}
        >
          <Toaster
            position="bottom-right"
            richColors
            duration={4000}
            closeButton
          />
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}